// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sfpmdtpwqnkxsfeikwpn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNmcG1kdHB3cW5reHNmZWlrd3BuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MTYwMjcsImV4cCI6MjA1OTE5MjAyN30.FrUp13okeXqqYTHCJnmja6ikEgsMT6Ey6AI73q8Io6Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);